version: 2
updates:
  # Update rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  # Update dependabot
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
