[project]
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "example"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
maturin = ">=1.8.1,<2"
uv = ">=0.5.14,<0.6"
jupyter = ">=1.1.1,<2"
jupyterlab = ">=4.3.4,<5"
polars = ">=1.17.1,<2"
pandas = ">=2.2.3,<3"
pyarrow = ">=18.1.0,<19"
plotly = ">=5.24.1,<6"
needletail = ">=0.6.1,<0.7"
