[project]
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "minimappers2"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
uv = ">=0.5.14,<0.6"
maturin = ">=1.8.1,<2"
