name: minimappers2

on:
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'minimappers2/src/'
      - 'minimappers2/Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - run: cd minimappers2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  build-manylinux-x64_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Test build
        uses: messense/maturin-action@v1
        env:
          RUSTFLAGS: -C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma
        with:
          rust-toolchain: nightly-2025-01-08
          maturin-version: '1.8.0'
          command: build
          args: -m minimappers2/Cargo.toml
